services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    command: ["meilisearch", "--no-analytics", "--log-level=INFO"]

  meili-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meili-client
    depends_on:
      - meilisearch
    environment:
      MEILI_HOST: meilisearch
      MEILI_PORT: 7700

volumes:
  meili_data:
